### ISSUE TITLE
Showing text email and password 

### ISSUE THREAD

**Issue by Prashant-2505** [sourabhsikarwar/Scene-Movie-Platform#1]
In login form it shows test mail and password i can fix this issue by removing it ( as a contributor of Gssoc' 23)

assign this issue to me 

![Screenshot (36)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/102030344/bdf0d43c-a1c4-4eb7-83b7-0548ec8c2eb4)

**Comment by sourabhsikarwar** [comment]
I intentionally kept this test credentials so that not everyone have to login with their main emails as many of them doesn't want to share the emails especially professionals. This test credentials can give them a look to the whole project without compromising the authentication feature.
