### ISSUE TITLE
 Footer icon doesn't move to Home page

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [sourabhsikarwar/Scene-Movie-Platform#116]
When we click on the footer icon, It doesn't move to home page.
Could you please assign this issue to me under GSSOC'23.

**Comment by Cypher1002** [comment]
how do i run this application on local host ?cant figure it out

**Comment by SoundaryaKoutharapu** [comment]
> how do i run this application on local host ?cant figure it out

These steps have worked for me.
1. git clone " url "
2. cd project-name
3.  npm install
4. npm start

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me
