### ISSUE TITLE
copyright year [ Gssoc 23 ]

### ISSUE THREAD

**Issue by mandliyarajendra11** [sourabhsikarwar/Scene-Movie-Platform#12]
we can use new Date().getFullYear() method for dynamic year change

![Screenshot (94)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/119125519/b03306c5-9fe2-4809-8dad-7ad29d705ebe)

**Comment by mandliyarajendra11** [comment]
I would like to work on this issue under gssoc'23

**Comment by deepeshgupta3257** [comment]
Please assign this task to me I can work on this issue and fix is and also I'm a contributor for GSSoC '23,
