### ISSUE TITLE
Finding difficulty on Local System

### ISSUE THREAD

**Issue by Singhal97dhruv** [sourabhsikarwar/Scene-Movie-Platform#128]
As i want to contribute to the repository i forked the repository but i  stucked after installing all npm modules but when i run it on local system it is not showing any pictures maybe i not configured firebase so pls anyone tell me how to configure it in my local system so that i can able to see all the images that is shown on the live project

**Comment by suzy-g38** [comment]
> As i want to contribute to the repository i forked the repository but i stucked after installing all npm modules but when i run it on local system it is not showing any pictures maybe i not configured firebase so pls anyone tell me how to configure it in my local system so that i can able to see all the images that is shown on the live project

You need to add env and then add the API key

**Comment by Singhal97dhruv** [comment]
can you tell me what is the location for the env file and what is the value of the api key
