### ISSUE TITLE
[Issue]: Missing details for Local Setup in README.md

### ISSUE THREAD

**Issue by Kalyan-velu** [sourabhsikarwar/Scene-Movie-Platform#136]
### Description: 

The README.md file in the repository does not provide enough details for setting up the project locally. Specifically, it does not mention how to create and configure the `.env` file with the movie API key details. This can cause confusion and errors for potential contributors who want to run the project on their own machines.

### Goals: 
The goal of this issue is to update the `README.md` file with clear and comprehensive instructions for creating and configuring the .env file with the movie API key details. This will make the local setup process easier and more user-friendly for contributors.

### Proposed Solution: 
The proposed solution is to add more details to the "Getting Started" section in README.md which explains how to clone the repository, install the dependencies, create the .env file, and obtain and set the movie API key details. It will also provide an example of how the .env file should look like.

GirlScript Summer of Code 2023
This issue is part of my contribution to GirlScript Summer of Code 2023. I am open to fixing this issue.

**Comment by Singhal97dhruv** [comment]
How to get the REACT_APP_API_KEY can u please tell

**Comment by Kalyan-velu** [comment]
from here [http://api.themoviedb.org/](http://api.themoviedb.org/)

**Comment by Singhal97dhruv** [comment]
And where would be the location of the env file
And please also can you tell what data we have to put in .env file

**Comment by Kalyan-velu** [comment]
in Root of the project where your package.json exists.
in the .env file 
```
REACT_APP_API_KEY=your moviedb api key
```

**Comment by Singhal97dhruv** [comment]
Ok now working thanks a lot.
