### ISSUE TITLE
[Feature]: Add a scroll to top navigation button

### ISSUE THREAD

**Issue by abhinav-m22** [sourabhsikarwar/Scene-Movie-Platform#162]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | There is an absence of a scroll-to-top button on the website.|
| **Describe the solution you'd like** | Add a small arrow button on the bottom corner of the page. |
| **Additional context** | The scroll-to-top nav button is a useful component of the web page as it routes the page back to the top on the main page. The website's user experience would be improved by the addition of this floating button. |

**Comment by mfatima05** [comment]
please assign this issue to me

**Comment by khushiminda** [comment]
as a ui.ux designer i find your snavbar is a little boring
i can make a carousel effect for yourr website to show various cool transitions

Please assign me this issue under gssoc 23 so that i can submit the PR
