### ISSUE TITLE
[Feature]: Create a server

### ISSUE THREAD

**Issue by suzy-g38** [sourabhsikarwar/Scene-Movie-Platform#171]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | Yes. |

When an API is called then if you go to the network tab you will find the API key, which is very sensitive information.
![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/62666287/fd1b9e24-14f2-4cb6-bcdd-c7a94ea48213)

| **Describe the solution you'd like** | Please present a concise and precise description of the solution you envision. |

Now the most feasible solution is having a backend server. From frontend, the request will be fired and at the backend, we will integrate the API key. As we already have a db in this project(the movie db), so we will get the information from there and return it to the frontend.

| **Describe alternatives you've considered** | Elaborate on any alternative solutions or features that you have already evaluated as potential approaches. |

We can also do this by migrating the entire codebase from react to next, as next has its own backend server so we can bind the API key at the next backend.

| **Additional context** | Include any supplementary information, contextual details, relevant screenshots, or supporting materials that can aid in better understanding and supporting your feature request. |

**Comment by PatilHarshh** [comment]
@sourabhsikarwar @suzy-g38  i also want to work with this issue please assign me as well,
