### ISSUE TITLE
[BUG]: Trailer video not responsive

### ISSUE THREAD

**Issue by Avinash905** [sourabhsikarwar/Scene-Movie-Platform#184]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

---

|  🐛   |   Bug report                         |
|-----|--------------------------------------|
| **Describe the bug** | The video of the trailer of the movie is not responsive on smaller devices. |
| **Location of the bug** | In the individual movie page |
| **Expected behavior** | The video should be responsive |

## Screenshots
![Screenshot (446)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/56786344/c11b7b2d-87ef-4457-a6e0-00965f1a133d)

**Comment by Avinash905** [comment]
I would like to work on this issue under GSSOC'23.

**Comment by Harshu467** [comment]
I want to contribute, Can your Please assign me this task?
