### ISSUE TITLE
Adding a scroll-to-top button [GSSOC'23]

### ISSUE THREAD

**Issue by huzaifa9999** [sourabhsikarwar/Scene-Movie-Platform#19]
please assign me the task to add a scroll to top button

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by deepeshgupta3257** [comment]
Please assign this task to me I can work on this issue and fix is and also I'm a contributor for GSSoC '23,

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.
