### ISSUE TITLE
[BUG]: Home page navigation after signing up

### ISSUE THREAD

**Issue by Avinash905** [sourabhsikarwar/Scene-Movie-Platform#213]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

---

|  🐛   |   Bug report                         |
|-----|--------------------------------------|
| **Describe the bug** | After user signs up the the user gets logged in and navigates to login page which is not required |
| **Location of the bug** | Sign up page |
| **Expected behavior** | After signing up the user should navigate to home page instead of login page. |

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Vsoni27** [comment]
I think now after signing up the user gets navigated to login page without getting logged in.
