### ISSUE TITLE
Website Redirects to Login Page Upon Refresh

### ISSUE THREAD

**Issue by Aarize29** [sourabhsikarwar/Scene-Movie-Platform#22]
Issue: Website Redirects to Login Page Upon Refresh

Description:
When accessing the website and subsequently refreshing the page, users are automatically redirected to the login page instead of remaining on the current page or being redirected to the expected page. This behavior is unexpected and disrupts the user experience.

Steps to Reproduce:

Open the website in a web browser.
Log in or navigate to a specific page within the website.
Refresh the page by clicking the refresh button or pressing the browser's refresh shortcut (e.g., F5).
Expected Result:
Upon refreshing the page, users should remain on the current page or be redirected to the expected page within the website while maintaining their logged-in state.

Actual Result:
After refreshing the page, users are redirected to the login page, requiring them to log in again.

Impact:
The issue negatively impacts user experience, as users are forced to log in repeatedly, interrupting their workflow and causing frustration. Additionally, it may discourage users from engaging with the website, resulting in a decrease in user engagement and potential loss of business.

Proposed Solution:
Investigate and resolve the issue causing the website to redirect users to the login page upon page refresh. Potential causes include incorrect session handling, authentication token expiration, or server-side configuration errors. Identify the root cause and apply the necessary fixes to ensure that page refreshes do not trigger unwanted redirects to the login page.

**Comment by Aarize29** [comment]
Could you please assign this issue to me

**Comment by Avinash905** [comment]
@sourabhsikarwar I would like to work on this issue so could you please assign the issue to me?
