### ISSUE TITLE
[Feature]:  Adding share functionality to the card

### ISSUE THREAD

**Issue by saikiranreddy201** [sourabhsikarwar/Scene-Movie-Platform#221]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | No, I want to improve the UI of the card |
| **Describe the solution you'd like** | I want to add a share button on the movie card so that one can share this card on multiple social media platforms which I believe will be a perfect add-on for this project |
| **Additional context** | The feature I have proposed can be achieved using the react-share package, multiple social media platforms such as WhatsApp, facebook, twitter can be added using that package! |

**Comment by Deepanshu0703** [comment]
Hey @sourabhsikarwar can you assign this task to me now

**Comment by saikiranreddy201** [comment]
Hey @sourabhsikarwar, I apologize for my absence from work recently as I had exams to attend to. I **assure** you that I will make up for it by submitting the PR within the next two days. Thank you for your understanding :)
