### ISSUE TITLE
[BUG]: User Profile

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [sourabhsikarwar/Scene-Movie-Platform#240]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

---

|  🐛   |   Bug report                         |
|-----|--------------------------------------|
| **Describe the bug** | The user profile seems to be a static template. The user name and email are fixed irrespective of the user. |
| **Location of the bug** | User Profile |
| **Expected behavior** | The user should be able to see his details |

## Screenshots (if any)
---
|     Screenshot 1 (if any)       |       Screenshot 2 (if any)     |
| :-----------------: | :------------------: |
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/83866602/a6e12cea-74a1-4d4b-a894-ebb9b702382d) | ![Screenshot 2](link) |

**Comment by Avinash905** [comment]
I can work on this issue under **GSSOC'23**.
