### ISSUE TITLE
[Feature]: Improve the lighthouse report score

### ISSUE THREAD

**Issue by Avinash905** [sourabhsikarwar/Scene-Movie-Platform#258]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | The performance and SEO metrics are quite low |
| **Describe the solution you'd like** | I would like to improve the performance and SEO of the website |

The current score is:
![Screenshot (502)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/56786344/6fc2d18a-def4-4ac3-beb2-18d734368a4d)

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by sourabhsikarwar** [comment]
@Avinash905 Kindly add some documentation or comments in the code and list of the steps you will take to work out this  optimization as this will help me and other contributors to understand how these practices can be done in the projects. Thanks in advance

**Comment by Avinash905** [comment]
> @Avinash905 Kindly add some documentation or comments in the code and list of the steps you will take to work out this optimization as this will help me and other contributors to understand how these practices can be done in the projects. Thanks in advance

Ok sure.
