### ISSUE TITLE
Cast on particular movie page

### ISSUE THREAD

**Issue by sourabhsikarwar** [sourabhsikarwar/Scene-Movie-Platform#268]

**Comment by mandliyarajendra11** [comment]
i did not understand task

**Comment by mandliyarajendra11** [comment]
> the API have a lot of information regarding a particular movie like actor/actress cast, director information, release dates, etc. The issue is revolving around the usage of this provided information and upgrading the UI of the app with this. Any doubts??

ok now i understand and able to work on this issue please assign me sir 🙂
