### ISSUE TITLE
Movie page UI optimization

### ISSUE THREAD

**Issue by sourabhsikarwar** [sourabhsikarwar/Scene-Movie-Platform#269]

**Comment by anamika7153** [comment]
@sourabhsikarwar I have made some changes and I want you to review them before merging.
I am providing some screenshots below. Mobile view looks okay to me so I haven't made any changes to that.

---
|     Before      |       After     |
| :-----------------: | :------------------: |
| Large screen
![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/f2e213cd-b78f-4a2c-9ea2-13fe68ecee5f) | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/eb578af5-9a14-4c12-95d0-544f4280f86c) |
| :-----------------: | :------------------: |
| Medium Screen 
![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/c82868e8-1ef3-4ae6-a9ab-131790908cb5) | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/e12945ed-88fd-4a11-95d0-4702e3b2296b) |

**Comment by sourabhsikarwar** [comment]
The center align content might not look good on the big screens. Its good for mobile view but for laptops it can be left aligned @anamika7153

**Comment by sourabhsikarwar** [comment]
Also share mobile view images also

**Comment by anamika7153** [comment]
> Also share mobile view images also

@sourabhsikarwar 

<img width="655" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/bb73f9e7-e019-4022-8198-a9cf9cef27ee">

**Comment by anamika7153** [comment]
> The center align content might not look good on the big screens. Its good for mobile view but for laptops it can be left aligned @anamika7153

Okay, so I will make the content left aligned.

**Comment by anamika7153** [comment]
@sourabhsikarwar  Shall I go ahead and make a PR?

**Comment by sourabhsikarwar** [comment]
the paragraph is left aligned, it should be in center for mobile screen and left aligned only for the bigger screens
@anamika7153

**Comment by anamika7153** [comment]
> the paragraph is left aligned, it should be in center for mobile screen and left aligned only for the bigger screens @anamika7153

okay

**Comment by anamika7153** [comment]
> The center align content might not look good on the big screens. Its good for mobile view but for laptops it can be left aligned @anamika7153

@sourabhsikarwar 
<img width="552" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/61b968e1-1156-4904-8439-face71f9605c">

**Comment by anamika7153** [comment]
> @sourabhsikarwar Shall I go ahead and make a PR?

@sourabhsikarwar  Is there anything else ??
