### ISSUE TITLE
[Feature]: Adding TV Shows page

### ISSUE THREAD

**Issue by anamika7153** [sourabhsikarwar/Scene-Movie-Platform#289]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | TV Shows page isn't redirecting anywhere |
| **Describe the solution you'd like** | Adding a TV Shows page that displays all the TV shows. |
| **Additional context** | I'll add categories like comedy, romance, drama, latest, etc and related content. |

**Comment by Nishitbaria** [comment]
Hey @sourabhsikarwar  please assign me this issue I will create a pull request within one day

**Comment by anamika7153** [comment]
> Hey @sourabhsikarwar please assign me this issue I will create a pull request within one day

@Nishitbaria I'm already working on it

**Comment by Nishitbaria** [comment]
> > Hey @sourabhsikarwar please assign me this issue I will create a pull request within one day
> 
> @Nishitbaria I'm already working on it 

Issue is created 14 days ago still you are not created the pr :(
