### ISSUE TITLE
[Feature]: Movie details in Movie Pages

### ISSUE THREAD

**Issue by anamika7153** [sourabhsikarwar/Scene-Movie-Platform#348]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | Currently, the movie page doesn't display any any details of the movie like cast, subtitle, genre, etc.  |
| **Describe the solution you'd like** | Adding a Details section below the movie banner. |
| **Describe alternatives you've considered** | Adding details like caste, genre, audio, duration, release date |

**Comment by mandliyarajendra11** [comment]
@sourabhsikarwar  i am already working on this issue - #268
