### ISSUE TITLE
[BUG]: Space between Back to Home button and footer

### ISSUE THREAD

**Issue by Avinash905** [sourabhsikarwar/Scene-Movie-Platform#353]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

---

|  🐛   |   Bug report                         |
|-----|--------------------------------------|
| **Describe the bug** | There is no space between Back to Home button and footer on error page |
| **Location of the bug** | Error page |
| **Expected behavior** | There must be some space between Back to Home button and footer |

## Screenshots (if any)
---
![Screenshot (543)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/56786344/980d7973-0e50-4c06-9978-d3b71607e3da)

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by sourabhsikarwar** [comment]
The footer need padding from top as it has very less space from other components also
