### ISSUE TITLE
[ PROJECT PROPOSAL] Anime and Manga section integration in website.

### ISSUE THREAD

**Issue by Pin4sf** [sourabhsikarwar/Scene-Movie-Platform#39]
# Anime and Manga Section
 We should add an Anime and Manga section in the Scene App.
 this will diversify our media content and will be first platform to have anime , movies and mangas together in one place.

### _**Benefits of this proposal**_ 
- No other entertainment platform have all in one media content.
- This will help gain more user who are anime fans.

## Features

- The Anime and Manga section will have upto date catalog.
- GogoAnime API integration.
- Import and save files to GitHub, Dropbox, Google Drive and One Drive.
- A comment section for users.

> Navbar and pages linking will also be done.

**Comment by REC-1104** [comment]
i also want to work on this issue

**Comment by Pin4sf** [comment]
> I also want to work on this issue .

Yes it would be really helpful for me I would like to collaborate with you for this task.
@sourabhsikarwar Please add this guy also in solving this issue.
