### ISSUE TITLE
[Feature]: chatbot icon

### ISSUE THREAD

**Issue by anamika7153** [sourabhsikarwar/Scene-Movie-Platform#506]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | Current position is overlapping scroll to top button and also it's doesn't give clarity for what purpose it is. |
| **Describe the solution you'd like** | I would like to change it's icon and position so that everything is user friendly and get accessible without making a mess. |

**Comment by 0xabdulkhalid** [comment]
Hi there @anamika7153 👋🏻 

I hope you are doing good, actually there's another issue which is already addressed this problem, Refer this for more details #499.

Thank you!

**Comment by anamika7153** [comment]
> Hi there @anamika7153 👋🏻
> 
> I hope you are doing good, actually there's another issue which is already addressed this problem, Refer this for more details #499.
> 
> Thank you!

@0xabdulkhalid you are right. I have added one mor thing in my issue (icon changing)  which is not included in your issue. So i guess i can work on this one. And you can work on the position.
