### ISSUE TITLE
[BUG]: Movie card showing double text

### ISSUE THREAD

**Issue by Palakkgoyal** [sourabhsikarwar/Scene-Movie-Platform#524]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

---

|  🐛   |   Bug report                         |
|-----|--------------------------------------|
| **Describe the bug** | On the website the movie cards are showing movie names twice |
| **Location of the bug** | It is occuring on the home page |
| **Expected behavior** | The name should appear only once |

## Screenshots (if any)
---
|     Screenshot 1 (if any)       |       Screenshot 2 (if any)     |
| :-----------------: | :------------------: |
| 
![Screenshot 2023-08-02 175953](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/116902573/6273a67d-67fd-41f7-a2d3-5fa9a28ee2fd)
 | ![Screenshot 2](link) |

Please provide any necessary screenshots to illustrate.

**Comment by anamika7153** [comment]
@Palakkgoyal I have already opened this issue #485
