### ISSUE TITLE
Home Page Movie Filter 

### ISSUE THREAD

**Issue by AKACHI-4** [sourabhsikarwar/Scene-Movie-Platform#63]
Hey 👋, I am a Gssoc'23 contributor 

Feature Request 
---

I would like to contribute a `card movie filter` on the home page of screen which will help users to find out different genres of movie interactively. a filter is already there But I think that is not highly eye picking.

Screenshot 
---
![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/99159580/bcdcd7a8-cb5e-4815-a1c0-dc0511716f5d)

> **Kindly assign it to me under _GSSOC'23_** 
> **I will surely complete it ASAP**

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

**Comment by AKACHI-4** [comment]
Hey @bhoomikhurana 👋 Thanks for your time But I am working on it ...

**Comment by AKACHI-4** [comment]
Home page is not loading !!
I don't know why it is happening I am trying to add feature through Github code spaces but What I found is the cards or different movie sections are properly loading. It is taking more time then expected. 

![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/99159580/296e9634-5bdf-4301-b90c-4938014d1cd6)
