### ISSUE TITLE
[Bug]: Social media links not working

### ISSUE THREAD

**Issue by accodes21** [sourabhsikarwar/Scene-Movie-Platform#69]
In the footer, by clicking on your name it doesn't redirect to your github page, this needs to be changed as it provides the user an opportunity to view your GitHub profile.
I would like to work on this under GSSOC'23
Please assign this to me.

**Comment by Apreksha** [comment]
Hey @sourabhsikarwar, I'm a GSSoC'23 contributor and a full stack developer. I can add links to the social media icons in the footer. Could you please assign this task to me?
