### ISSUE TITLE
Add a functionality to the main logo(button) of the web app

### ISSUE THREAD

**Issue by abhinav-m22** [sourabhsikarwar/Scene-Movie-Platform#93]
Add a functionality to redirect the website to the main home page after clicking on the logo.
This will provide an easy way to the user to navigate through the home page via different pages

Image reference:

<img width="949" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/113239388/b8879057-0210-48e1-9f79-a583ca2a6183">

I want to work on this issue.
Please assign me task under GSSoC'23.

**Comment by mfatima05** [comment]
please assign this issue to me
