### ISSUE TITLE
Update social media icons

### ISSUE THREAD

**Issue by Aryan123-rgb** [sourabhsikarwar/Scene-Movie-Platform#95]
1. Add hovering effect on the social median icons on the footer section
2. Make the icons working by attaching your profile links in it 

Assign this issue to me under gssoc 2023

**Comment by Aryan123-rgb** [comment]
@sourabhsikarwar Please assign this to me . It should not take too long to fix such a small issue.

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

**Comment by VijayalakshmiGanesh** [comment]
I would like to work on this issue if its not done yet. Could you please assign it to me under GSSOC label

**Comment by KamalSritha-04** [comment]
Please assign this issue to me under GSSOC'23.

**Comment by Michelle031** [comment]
Please please can I be assigned this issue

**Comment by mfatima05** [comment]
please assign this issue to me

**Comment by tripathishipra** [comment]
Hi , I am contributor under GSSOC'23 and I am eager to showcase my skills and make a meaningful contribution to this project.
Kindly assign me this issue@sourabhsikarwar
